spring.application.name=JobsSearchPortal
server.port=8081

# postgresql Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/learning
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0


jwt.secret=bajkbhqivandkvg689vjvou@#vksyhijlbliutgplk8JNLohainp45eGlkhUGlkHvkP
jwt.expiration.ms=86400000

refresh.jwt.secret=bajabaljivandkvg689vjvou@#vksyvahvpjNLohainp45eGlkcmsjGlkHP
refresh.jwt.expiration.ms=259200000